### ISSUE TITLE
Automated Save/Restore

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-fast-interrupt#140]
Raised by AIA group as potentially useful for fast interrupt group in email.

- Shadow GPRs are replaced with automated hardware based save/restore sequences. While the savings are significant to interrupt latency, its implementation has been limited to  microcontrollers, and as such will not be an appropriate candidate for AIA. It has the hazard that it needs to be recoverable in case a higher priority interrupt comes along. This could be a custom feature implemented in a hart.

**Comment by kasanovic** [comment]
If cores add push/pop instructions for code-size savings, then variants of these could be added to improve context save/restore performance.  These would be explicitly added in software in handlers versus automatic by hardware in interrupt handling.
