### ISSUE TITLE
Need to add commentary on use of bare-S mode (satp=0) versus proposed N-extension

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-fast-interrupt#141]
Bare S-mode (no MMU, satp=0) can be used in microcontrollers to allow hardware delegation of interrupts out of M-mode.   Bare S-mode has already been ratified as part of privileged architecture.  There are also proposals to add S-mode PMP support to allow an RTOS running in S-mode to isolate itself from tasks running in U-mode.  The proposed N-extension would also add user-mode interrupts and traps, but has not been ratified and is not currently being advanced.

This issue records that CLIC spec text should add context explaining this.

**Comment by dansmathers** [comment]
created pull #146 to close this issue.

**Comment by kasanovic** [comment]
Closed by #141
