### ISSUE TITLE
Clarify isolation mechanism over CLIC memory mapped registers 

### ISSUE THREAD

**Issue by joxie** [riscv/riscv-fast-interrupt#156]
Per discussions in fast interrupt TG we are expecting memory mapped registers to be aliased in M/S mode systems, it would be good to provide some clarity in spec to avoid confusion.

For example, below statements may make people think that CLIC is enforcing priv mode identifier on memory bus when accessing these registers:

All CLIC-memory mapped registers are visible to M-mode. Interrupt registers clicintip[i], clicintie[i], clicintattr[i], clicintctrl[i] configured as M-mode interrupts are not acessible to S-mode and U-mode. Interrupt registers clicintip[i], clicintie[i], clicintattr[i], clicintctrl[i] configured as S-mode interrupts are not acessible to U-mode.

In S-mode, any interrupt i that is not accessible to S-mode appears as hard-wired zeros in clicintip[i], clicintie[i], clicintattr[i], and clicintctl[i].

Another example is that cliccfg might be RO for S mode and RW for M mode, but memory map says it is RW:

  0x0000         1B          RW        cliccfg

**Comment by kasanovic** [comment]
Will add clarification to spec about how memory apertures are intended to be protected across privilege modes.

**Comment by kasanovic** [comment]
In TG meeting 6/8/2021 we realized the discussion of memory apertures was incorrectly removed from the spec, and need to be reinstated to remove this confusion.

**Comment by kasanovic** [comment]
Added back text on memory apertures in commit https://github.com/riscv/riscv-fast-interrupt/commit/f2c9a1e7ef6fab9eb69bff39b0c0f1d677dc4561 .  Still needs a little clean up to help clarify these issues.
