### ISSUE TITLE
Pseudo-code for xnxti

### ISSUE THREAD

**Issue by billhuffman** [riscv/riscv-fast-interrupt#165]
Seems like the pseudo-code just for csrrsi rd, mnxti, uimm[4:0] should be:

    // Pseudo-code for csrrsi rd, mnxti, uimm[4:0] in M mode.
    mstatus |= uimm[4:0]; // Performed regardless of interrupt readiness.
    if (clic.priv==M && clic.level > mcause.pil && clic.level > mintthresh.th
         && (cliccfg.nvbits==0 || clicintattr.shv==0) ) {
       // There is an available, non-hardware-vectored interrupt.
       if (uimm[4:0] != 0) {
         // Commit to servicing the available interrupt.
         mintstatus.mil = clic.level; // Update hart's interrupt level.
         mcause.exccode = clic.id;    // Update interrupt id in mcause.
         if (clicintattr[clic.id][1] == 1) {
           clicintip[clic.id] = 0;    // clear edge interrupt
         }
       }
       rd = TBASE + XLEN/8 * clic.id; // Return pointer to trap handler entry.
    } else {
       // No interrupt, or a selectively hardware vectored interrupt, or in non-CLIC mode.
       rd = 0;
    }
 
I changed the comments not to refer to tail-chaining.  I think the real meaning of doing the write is that we’re committing to service the available interrupt (by turning off clicintip for edge).  It’s only indirectly related to tail-chaining.
 
We either have to comment about what other instruction versions do or make the pseudo-code harder to read by making it work for all csr instruction types.

**Comment by billhuffman** [comment]
The text says:

      If the pending interrupt is edge-triggered, hardware will automatically clear the corresponding pending bit only
      when software uses a csrrsi/csrrci xnxti instruction to select this interrupt and return its entry address. 

But I think we mean for it to say:

     If the pending interrupt is edge-triggered, hardware will automatically clear the corresponding pending bit when
     there is a write to the xnxti CSR.

That is, it's not just csrrsi/csrrci that cause the clear but any write, including csrrs, csrrc, csrrw, or csrrwi.

Or possibly the pending bit should be included a couple of paragraphs up when other side-effects are considered.

**Comment by dansmathers** [comment]
reopening

**Comment by dansmathers** [comment]
closing with pull #169
