### ISSUE TITLE
Unprivileged spec says there are no read or write side effects

### ISSUE THREAD

**Issue by billhuffman** [riscv/riscv-fast-interrupt#166]
Section 10.1 of the Unprivileged Spec states, non-normatively, that no CSR registers currently have read or write side-effects.  xnxti has write side-effects and we should probably change the statement.

**Comment by aswaterman** [comment]
The unpriv spec does say "thus far", but indeed even that will be invalidated by the eventual completion of CLIC.  Fixed in https://github.com/riscv/riscv-isa-manual/commit/ae98d0f334930d8c6c4c44960fa2a2209b70e75c
