### ISSUE TITLE
Inconsistency in Parameters

### ISSUE THREAD

**Issue by billhuffman** [riscv/riscv-fast-interrupt#171]
Chapter 6 has a parameter, CLICCFGLBITS that says it's 0-CEIL(lg2(CLICLEVELS)) and that it's the number of bits implemented for cliccfg.nlbits.  This ties cliccfg.nlbits and the number of levels available.   But at the Sept 14 meeting, we said that nlbits could be hardwired to 0 or 8 and that 8 allowed any number of levels, not just 256.  If the Sept 14 discussion is correct, this parameter needs updating.

**Comment by dansmathers** [comment]
closed bvy #369
