### ISSUE TITLE
Pseudo-code for csrrsi rd, mnxti, uimm[4:0] in M mode

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-fast-interrupt#179]
Should the pseudo-code in section 5.8 when servicing an interrupt include:

`       mcause.Interrupt = 1;
`

Obviously this CSR access would normally be done within an active interrupt handler so we would expect `mcause.Interrupt` to be set already, but it might not be if the handler has modified it.

Thanks.

**Comment by kasanovic** [comment]
TG agrees that bit should be set.  The main justification is that the handler to which the code will presumably jump might expect that bit to be set on entry.
