### ISSUE TITLE
Write to xcause behaviour?

### ISSUE THREAD

**Issue by divan0v** [riscv/riscv-fast-interrupt#188]
Clarify, please, is state of xstatus.xpp/xstatus.xpie changed when software writes to xcause CSR?

Section 5.7: "The mcause.mpp and mcause.mpie fields mirror the mstatus.mpp and mstatus.mpie fields, and are aliased
into mcause to reduce context save/restore code."

Thanks

**Comment by dansmathers** [comment]
created pull #189 for issue #188 - clarify writes to xcause.mpp/mpie fields.  Adding a note to with similar language used in the privilege specification in describing read/write accesses to sstatus/mstatus fields.
We will try to discuss this pull in the next TG meeting 1/4/2022

**Comment by kasanovic** [comment]
Closed with #189
