### ISSUE TITLE
u* CSRs and bitfields related to user mode interrupts

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-fast-interrupt#200]
This question is related to https://github.com/riscv/riscv-fast-interrupt/issues/160. 

If I have a hart supporting only M-mode and U-mode and furthermore assuming that the N-extension references will be removed from the CLIC specification, can I assume that the following will be part of the clean-up requested in #160?

- clicintattr.mode == 2'b00 will be declared as a reserved value
- The section about 'user mode CLIC regions' will be removed all together
- utvt, unxti, uintstatus, uintthresh, uscratchcsw, uscratchcswl will not exist
- (ustatus, uie, utvec, uscratch, uepc, ucause, utval, uip will not exist)
- minstatus.uil will be made reserved (i.e. the uil bitfield will be removed, but the corresponding mintstatus bits will be marked as reserved)

**Comment by kasanovic** [comment]
PR #292 addresses this issue.
