### ISSUE TITLE
Question about vectored interrupt (vertical trap)

### ISSUE THREAD

**Issue by divan0v** [riscv/riscv-fast-interrupt#210]
Clarify, please, time moment when CSRs (xcause.(code|xpil|...), xtval, xintstatus and others) are updated for bad vectored interrupt in vertical trap case?

Example to explain question:

1. Current privilege mode is 'S', medeleg=0.
2. Clic interrupt is active with 'shv' attribute (handler privilege mode for this interrupt is also 'S').
3. Interrupt is taken, the hart switches to handler mode 'S', sets scause.xinhv, clears sstatus.sie (as described in section 5.4).
4. Hart fetches interrupt handler address, but fetch is not successful.
5. Hart takes exception and go to trap handler (to 'M' mode).
6. Exception is processed in trap handler.
7. MRET is executed (with scause.xinhv=1), so hart fetches interrupt handler address again, fetch is successful (scause.xinhv cleared).
8. Hart now in interrupt handler.

Do I understand correctly that time moment for updating CSRs (scause.(code|xpil|...), stval, sintstatus and others) is equal to step #3?

If it's right please extend this line: 
"_On the other hand, writing 1 to clicintattr[i].shv sets interrupt i to vectored. When these interrupts are
taken, the hart switches to the handler’s privilege mode, sets the hardware vectoring bit xinhv in xcause of the
handler privilege mode, and clears xstatus.xie_."

Thanks

**Comment by kasanovic** [comment]
Closed by https://github.com/riscv/riscv-fast-interrupt/commit/a5c5a9f401e55e63ff49de4369226a0f737db4d6
