### ISSUE TITLE
xtval - is mtval = 0 a compliant implementation?

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-fast-interrupt#223]
Section 5.4. New xtvec CSR Mode for CLIC states the following:

> If there is an access exception on the table load, both xtval and xepc holds the faulting address.

The RISC-V privileged specification states:

> If the hardware platform specifies that no exceptions set mtval to a nonzero value, then mtval is hardwired to zero.

Could you please confirm that with CLIC an implementation that has mtval == 0 is still compliant to the CLIC spec.

**Comment by kasanovic** [comment]
Yes, we allow implementations to keep mtval==0, though recommend writing with faulting address in systems with demand paging. See PR #227.
