### ISSUE TITLE
clic.priv/clic.level/clic.id not well defined in mnxti pseudo-code

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-fast-interrupt#233]
// Pseudo-code for csrrsi rd, mnxti, uimm[4:0] in M mode.
 mstatus |= uimm[4:0]; // Performed regardless of interrupt readiness.
 if (clic.priv==M && clic.level > mcause.pil && clic.level > mintthresh.th

Should probably add a note above the pseudo-code that clic.priv/level/id represents the highest-ranked interrupt currently present in the CLIC  (using same wording as in 8.1 General Interrupt Overview).

**Comment by kasanovic** [comment]
Closed by #234.
