### ISSUE TITLE
mscratchcsw defined using mcause.mpp instead of mstatus.mpp

### ISSUE THREAD

**Issue by pashenden** [riscv/riscv-fast-interrupt#240]
The pseudocode definition of csrrw access to the mscratchcsw CSR uses mcause.mpp for the previous privilege level. However, if mtvec.mode is not CLIC mode, mcause.mpp does not mirror mstatus.mpp and is read as 0. Should the definition use mstatus.mpp instead of mcause.mpp, so that the operation is the same in non-CLIC mode?

**Comment by kasanovic** [comment]
mscratchcsw should not exist in non-CLIC mode, need to clarify text

**Comment by dansmathers** [comment]
closed by pull #258?  default text that CSRs added by CLIC mode appear zero unless specified elsewise.

**Comment by kasanovic** [comment]
Issue addressed by above commits.
