### ISSUE TITLE
Debug trigger behavior

### ISSUE THREAD

**Issue by divan0v** [riscv/riscv-fast-interrupt#244]
Clarify, please, debug trigger behavior for the following case. Let's all clicinttrig regs are implemented as hard-wired zero, i.e. interrupt triggers are not implemented. Let's address of some interrupt handler (with clicintattr[i].shv=1) is equal to 'A'. Should match control trigger with match type 'execute address' raise when hardware vectoring is occurred for address 'A'?

**Comment by divan0v** [comment]
Sorry for inaccurate question. A more clear question is: 
1. Should match control trigger with match type 'execute address' raise when hardware vectoring is occurred for xtvt[i]?
2. Should match control trigger with match type 'load address or load data' raise when hardware vectoring is occurred for xtvt[i]?

**Comment by kasanovic** [comment]
1). is correct.  The hardware table read is treated as an instruction fetch.  This is an optional hardware feature whether breakpoints/triggers are supported on hardware table reads.  See #228.

If the table was read with a regular load instruction, then this is treated like any other load wrt debug.
