### ISSUE TITLE
The PC formula in section 3.4 does not have the case for selective HW vectoring, clarification is needed.

### ISSUE THREAD

**Issue by chuanhua** [riscv/riscv-fast-interrupt#25]
The following PC formula still does not have the effect of selective HW vectoring described in section 2.3.4. Please clarify the selective HW vectoring concept in this formula table in section 3.4.
-------------------------------------------------------

mtvec   Action on Interrupt
 aaaa00  pc := OBASE                (original non-vectored CLINT mode)
 aaaa01  pc := OBASE + 4 * exccode      (original vectored CLINT mode)
 000010  pc := NBASE                           (non-vectored CLIC mode)
 000011  pc := M[TBASE + XLEN/8 * exccode)] & ~1  (vectored CLIC mode)
 xxxx1?  (xxxx!=0000)                            Reserved

 OBASE = mtvec[XLEN-1:2]<<2 # Original vector base was at least 4-byte aligned.
 NBASE = mtvec[XLEN-1:6]<<6 # New vector base is at least 64-byte aligned.
 TBASE = mtvt[XLEN-1:6]<<6  # Trap vector table base is at least 64-byte aligned.
-------------------------------------------------
Thanks.

Chuanhua
Andes Technology

**Comment by dansmathers** [comment]
Now in section 4.4 of draft-20200423, updated to show effect of selective HW vectoring.

mtvec   Action on Interrupt
 aaaa00  pc := OBASE                              (original non-vectored basic mode)
 aaaa01  pc := OBASE + 4 * exccode                (original vectored basic mode)

 000011                                           (CLIC mode)
         (non-vectored)
         pc := NBASE                                    if clicintattr[i].shv = 0
                                                        || if cliccfg.nvbits = 0
                                                           (vector not supported)
         (vectored)
         pc := M[TBASE + XLEN/8 * exccode)] & ~1        if clicintattr[i].shv = 1

 000010                                           Reserved
 xxxx1?  (xxxx!=0000)                             Reserved

 OBASE = mtvec[XLEN-1:2]<<2   # Original vector base was at least 4-byte aligned.
 NBASE = mtvec[XLEN-1:6]<<6   # New vector base is at least 64-byte aligned.
 TBASE = mtvt                 # Trap vector table base is aligned proportionally
                              # to the maximum number of interrupts (see details
                              # below).
