### ISSUE TITLE
xinhv or inhv?

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-fast-interrupt#271]
The CLIC specification refers to '_x_inhv in _x_cause' and to '_x_inhv' in many places.

This would imply the following CSR + bitfield names: ucause.uinhv, scause.sinhv, mcause.minhv.

At the same the spec also sometimes just mentions 'inhv' and also ucause.INHV(), scause.INHV(), mcause.INHV().

This seems inconsistent; I would expect xinhv instead of inhv and ucause.UINHV(), scause.SINHV(), mcause.MINHV().

**Comment by kasanovic** [comment]
Closed with https://github.com/riscv/riscv-fast-interrupt/pull/273
