### ISSUE TITLE
CSIP #12 to #16

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-fast-interrupt#277]
The revision history does not state that the CSIP interrupt ID was changed from 12 to 16 on 29th August 2022. This is an important change and should be explicitly stated.

**Comment by JamesKenneyImperas** [comment]
Can you also clarify whether the CSIP in its new location behaves any differently to other local interrupts (number 17 upwards) or is it now really just another local interrupt that happens by convention to be called CSIP?

Thanks.

**Comment by dansmathers** [comment]
I updated the revision history to state CSIP interrupt ID was changed from 12 to 16.   
leaving this issue open to discuss your second question.   My understanding is that all the interrupts on the CLIC behave the same and the CLIC Interrupt ID ordering recommendations are just conventions for software compatibility, but we should probably add more text to clarify that.

**Comment by dansmathers** [comment]
copying [JamesKenneyImperas](https://github.com/JamesKenneyImperas) comment from commit to here and reopening this issue for easier tracking in TG meetings
:
This is a minor point, but I think it would help readability if a consistent and precise name was used to describe interrupts with id 16 and above in this specification.

In this section, they are referred to as "external interrupts". In section 3.2, they are referred to as "local interrupts". In section 3, they are referred to as "local external interrupts".

Thanks.

**Comment by kasanovic** [comment]
Closed with https://github.com/riscv/riscv-fast-interrupt/commit/1dc8432d6bf28b584deae84437d61f51c5f53f01
