### ISSUE TITLE
Single stepping an access to mnxti when dcsr.stepie==0

### ISSUE THREAD

**Issue by silabs-oysteink** [riscv/riscv-fast-interrupt#291]
When single stepping with dcsr.stepie==0, interrupts are disabled and no interrupt should be taken while executing the stepped instruction. 

What is the expected behavior of a CSR instruction accessing mnxti during a single step? Would it always behave as currently documented in the CLIC spec, or should it honor the dcsr.stepie bit and always return zero during a step if dcsr.stepie==0 ?

**Comment by dansmathers** [comment]
I would expect it would always behave as currently documented in the CLIC spec.  It behaves as specified even if xstatus.xie is 0 so I think when dcsr.stepie is 0, it would be no different.  Do you agree? We should discuss in the task group if additional clarification is required.

**Comment by silabs-oysteink** [comment]
Sounds good, I agree that with the behavior specified for xstatus.xie it should also not regard dcsr.stepie.

**Comment by kasanovic** [comment]
I agree with this rationale.
