### ISSUE TITLE
Change addresses of mintstatus, sintstatus, uintstatus

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-fast-interrupt#294]
The current proposed addresses for CSRs `mintstatus`, `sintstatus`, and `uintstatus` place them in the middle of an unused region of read-only CSRs.  See:
https://docs.google.com/spreadsheets/d/1E6hXv76BH2mcMQUyT4h1qyIPf-rY76DixtnyvZ24umg/

Large regions of CSR addresses should be kept open for possible future arrays of CSRs (such as `hpmcounter*` and `hpmcounter*h`).  To avoid them becoming an obstacle, it would be better for `mintstatus`, `sintstatus`, and `uintstatus` to be at locations 0xFB1, 0xDB1, and 0xCB1, respectively.

**Comment by kasanovic** [comment]
Closed with #300
