### ISSUE TITLE
How are CLIC-only CSRs and fields handled in CLINT mode?

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-fast-interrupt#303]
State is preserved on CLIC<->CLINT mode changes.

Text says they read as zero, but no description of behavior on writes.  Should probably not be possible to write a CLIC-only CSR in CLINT mode.

Could alternatively trap on any access (read or write) to CLIC-only CSRs in CLINT mode.

**Comment by dansmathers** [comment]
saw this in an email thread about upcoming changes to be included in priv spec 1.13.  "I was under the impression that it will no longer require illegal instruction exceptions on attempts to access undefined CSRs."

If priv spec removes illegal instruction exceptions on attempts to access undefined CSRs, probably shouldn't trap on accesses to CLIC-only CSRs in CLINT mode?

**Comment by dansmathers** [comment]
Note this behavior in CLIC mode to CLINT only CSRs: Writes to xie/xip will be ignored and will not trap (i.e., no access faults). xie/xip always appear to be zero in CLIC mode.

**Comment by kasanovic** [comment]
When not in CLIC mode, behavior of CLIC-only CSRs should be same as if CLIC was not implemented, so should be treated as a "reserved" operation.   The value in the CSRs after switching from CLIC->CLINT->CLIC mode should be treated as "reserved" also, i.e., the value is undefined.
