### ISSUE TITLE
Descriptions of xideleg and xedeleg look incorrect

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-fast-interrupt#305]
The descriptions of `xideleg` and `xedeleg` registers in this specification look incorrect. Each of sections 4.7, 5.2 and 6.2 imply that `xideleg` and `xedeleg` registers for M mode, S mode and U mode (with N extension) are present if that mode is present. This is not consistent with the Privileged Specification.

I think that `xedeleg` registers are irrelevant to this specification and all references to them should be removed.

For interrupt delegation registers, `mideleg` should be present only if either S-mode is present or U-mode with the N extension is present. `sideleg` should be present only if U-mode with the N-extension is present. There is no `uideleg` (or `uedeleg`) register - CSR numbers 2 and 3 correspond to `frm` and `fcsr`.

**Comment by kasanovic** [comment]
Closed by #306.
