### ISSUE TITLE
Typos in preemptible horizontal interrupt handler

### ISSUE THREAD

**Issue by christian-herber-nxp** [riscv/riscv-fast-interrupt#315]
in Section 10.2. Inline Interrupt Handlers and "Interrupt Attribute" for C:

`interuppt` instead of `interrupt.`

also, there is restore `s0`, which was never stored. Assume this is supposed to be on `a0`, so instead of 

`lw s0, OFFSET(sp)`
 
replace with 

`lw a0, OFFSET(sp)`

**Comment by dansmathers** [comment]
thanks for pointing it out
