### ISSUE TITLE
Script m vs plain m

### ISSUE THREAD

**Issue by billhuffman** [riscv/riscv-fast-interrupt#32]
The spec is written with 'm', 's', and 'u' as prefixes and a script 'm' as a generic prefix to refer to any of the three.  Most places it's possible to figure out whether an 'm' is script or plain.  But some places it's quite confusing.  In some fonts, it's very difficult to be sure of the difference.  Perhaps in some fonts they are actually identical.

I believe the privilege spec uses 'x' as the prefix to stand for any of 'm', 's', or 'u'.  To avoid confusion for all time :-) this spec should be changed, probably to the same pattern of using 'x'.

**Comment by dansmathers** [comment]
draft 20200423 seems to have cleaned up all generic references by using 'x' to stand in for any of 'm', 's', or 'u'.  Please comment if you still see any.  Thanks.
