### ISSUE TITLE
clarify interaction of CLIC with RNMI

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-fast-interrupt#320]
Section 4.10 (Resumable Non-Maskable Interrupts) says:

> The resumable NMI (RNMI) extension adds additional mnepc, mncause, and mnstatus CSRs. When in CLIC mode, *the RNMI retains the CLIC’s additional state in the mncause and mnstatus CSRs* to allow CLIC interrupts to be resumed.

Please can you make it explicit exactly what state is retained here and restored by MNRET?

Thanks.

**Comment by kasanovic** [comment]
It is the same addition as to the original CLINT cause and status, but we can add explicit text for this.

**Comment by dansmathers** [comment]
fixed will pull #328
