### ISSUE TITLE
Are xintstatus registers writable?

### ISSUE THREAD

**Issue by billhuffman** [riscv/riscv-fast-interrupt#33]
The numbers given to the xintstatus registers, 0x345, 0x145, and 0x045 are writable registers, but the description says all the fields are read-only.  Could that be made clearer in the spec?

**Comment by kasanovic** [comment]
These should be read only. - will change.

**Comment by dansmathers** [comment]
draft 20200423 lists xintstatus as:
(NEW) 0xm??   xintstatus   Current interrupt levels

This issue can be closed and tracked by issue #42: Address of xintstatus CSR
The address for xintstatus is listed as 0xm?? at the top of section 4. Can you please update this to reflect the correct address?

**Comment by Kevin-Andes** [comment]
Please refer to issue #88.
