### ISSUE TITLE
stateen register required to block access to new ssclic CSRs?

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-fast-interrupt#345]
ssclic adds stvt, snxti, sintstatus, sintthresh, sscratchcsw, sscratchcswl CSRs.  Do these new supervisor CSRs have to be protected by the Smstateen extension and documented in clic spec?  Add documentation like for JVT CSR in Zcmt extension?

**Comment by kasanovic** [comment]
Closed with https://github.com/riscv/riscv-fast-interrupt/commit/a62512916a6b42e9a37bc963933ec03a21b7a031
