### ISSUE TITLE
Reserved ranges in memory mapped registers

### ISSUE THREAD

**Issue by christian-herber-nxp** [riscv/riscv-fast-interrupt#351]
The Smclic section is specific on which memory mapped addresses are considered reserved. 
Same is not the case for Ssclic and Suclic. There, some regions are not explicitly listed (0x0001 - 0xFFF)

In fact, I believe the first reserved region in Smclic is incorrect. Instead of 
> ###   0x0008-0x003F              reserved    ###
should be 
> ###   0x0001-0x003F              reserved    ###
As there is only a single byte reserved for smclicconfig

**Comment by kasanovic** [comment]
Closed by #352
