### ISSUE TITLE
Is there a specification for mnstatus.mpp and mnstatus.mpie?

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-fast-interrupt#355]
Section 4 says:

> The `mncause.mpp` and `mncause.mpie` fields mirror the `mnstatus.mpp` and `mnstatus.mpie` fields, and are aliased into `mncause`.

The latest RNMI specification I've found (0.4) states that `mnstatus` has fields `MNPP`, `MNPV` and `NMIE` only. Is there a more recent version of the RNMI specification describing the fields mentioned here? If so, can you point me at it?

Thanks.

**Comment by dansmathers** [comment]
I only found this.
https://github.com/riscv/riscv-isa-manual/blob/main/src/rnmi.adoc
Plan to discuss this question in TG meeting.

**Comment by kasanovic** [comment]
RNMI spec has been stalled waiting ACT and SAIL resources.  We are trying to unblock the RNMI spec now.

**Comment by kasanovic** [comment]
There should actually be no interaction between resumable NMI (RNMI) and the fast interrupts section, and the sections regarding NMI (both non-resumable and resumable) will be re-written.  The RNMI CSRs are separate from the fast interrupts CSRs and so the state does not need to be saved in the RNMI registers.  This makes the design of the RNMI extension orthogonal to the core's general interrupt scheme.
