### ISSUE TITLE
Is CLIC register access via indirect CSR Access mandatory?

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-fast-interrupt#377]
The (new) chapter "CLIC register access via indirect CSR Access" states the following:

> A CSR accessible via one method may or may not be accessible via the other method such as memory-mapped access.

Does the above sentence also allow for a compliant implementation in which the stated CSRs are only accessible via memory-mapped access and not via indirect CSR access (as it was in the previous specification version)?

If not then I would suggest to replace the above sentence with:

> A CSR accessible via _indirect CSR access_ may or may not be accessible via _another_ method such as memory-mapped access.

**Comment by dansmathers** [comment]
Good point.  closed by pull #387.
