### ISSUE TITLE
clicintctrl vs. clicintctl

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-fast-interrupt#380]
The current specification uses different spelling for the (assumed) same register: clicintctrl vs. clicintctl.

Can all occurrences of 'clicintctrl' be renamed to 'clicintctl'?
Can 'CLICINTCTRL parameters' be renamed to 'CLICINTCTL parameters'?

**Comment by dansmathers** [comment]
fixed by pull #382
