### ISSUE TITLE
Titles of indirect register access sections

### ISSUE THREAD

**Issue by christian-herber-nxp** [riscv/riscv-fast-interrupt#383]
Section [3. CLIC register access via indirect CSR Access](https://github.com/riscv/riscv-fast-interrupt/blob/master/clic.adoc#clic-register-access-via-indirect-csr-access) is really M-mode CLIC Register Access via Indirect CSR Access. Renaming this would get it consistent with [4. S-mode CLIC Register Access via Indirect CSR Access](https://github.com/riscv/riscv-fast-interrupt/blob/master/clic.adoc#s-mode-clic-register-access-via-indirect-csr-access)

**Comment by dansmathers** [comment]
closed by #386
