### ISSUE TITLE
Address of xintstatus CSR

### ISSUE THREAD

**Issue by jm4rtin** [riscv/riscv-fast-interrupt#42]
The address for xintstatus is listed as 0xm?? at the top of section 4. Can you please update this to reflect the correct address? I believe it is 0xm46 (at least according to Spike).

**Comment by JamesKenneyImperas** [comment]
I would like to have this clarified as well.

**Comment by Kevin-Andes** [comment]
Assigned xintstatus CSR to 0xm46, where m is the nibble encoding the privilege mode (M=0x3, S=0x1, U=0x0).

**Comment by Kevin-Andes** [comment]
#88
