### ISSUE TITLE
CLIC reset behavior

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-fast-interrupt#47]
Except for one reference to the cliccfg register, there is no mention of reset behaviour in the specification. Is all other state unknown at reset?

**Comment by kasanovic** [comment]
Needs clarification in spec.
General model in RISc-V has been mandatory reset state is minimized, platforms or company policy might add additional reset requirements.

**Comment by kasanovic** [comment]
The general privileged architecture states that mstatus.mie is reset to zero, so coming out of reset interrupts will not be enabled.

For an S-mode only execution environment, the EEI should specify that status.sie is also reset on entry (it is then responsibility of EEI implementation to ensure that is true before beginning execution in S-mode).  Similarly for other lower-mode execution environments.

**Comment by kasanovic** [comment]
The spec could be clarified to have a separate reset section covering these issues.

**Comment by kasanovic** [comment]
Closed by pull #137
