### ISSUE TITLE
Clarify interrupt selection

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-fast-interrupt#52]
Section 3.7 describes presentation of a single interrupt to the core like this:

> To select an interrupt to present to the core, the CLIC hardware combines the valid bits in clicintattr.mode and clicintctl to form an unsigned value, then picks the global maximum across all pending-and-enabled interrupts based on this value. Next, the cliccfg setting determines how to split the maximum clicintctl value into interrupt level and interrupt priority. Finally, the interrupt level of the selected interrupt is compared with the interrupt-level threshold of the associated privelege mode to determine whether it is qualified or masked by the threshold (and thus no interrupt is presented).

Please can you explicitly state what _enabled_ means in this context? I assume it is `clicintie[i]` for the interrupt _and_ the relevant `mstatus.xie` bit, but this is not stated.

**Comment by Kevin-Andes** [comment]
Yes, both clicintie[i] and mstatus.xie should be enabled. clicintie[i] is the individual control bit while mstatus.xie is a global control bit for that particular mode (only valid in the corresponding mode).
This will be clarified in the spec later.
