### ISSUE TITLE
Some general issues

### ISSUE THREAD

**Issue by MoonbaseOtago** [riscv/riscv-fast-interrupt#57]
(I'm working through a basic implementation)

1) location
I want to reiterate the issue around knowing where a hart's CLIC M/S/U regions are located - I'd like to suggest that we probably need not just mclicbase but sclicbase/uclicbase (where appropriate) too - they're cheap because they're read-only

2) machine mode alignment
the machine mode CLIC space needs to be protected from S/U accesses with a PMP, they have their own (implementation defined) alignment constraints - it's probably worth requiring that in systems with S and/or U modes that:
a) the region containing all the hart's machine mode CLIC spaces can be mapped with one PMP, and
b) that there is a spare PMP available for this purpose

3) supervisor/user/(hypervisor?) mode alignment 
I think that this is already taken care of but it's worth making sure that a VM page (4k) alignment is required for the bases of each S/U mode CLIC region so that they can be mapped through the TLBs  (especially on user mode)

4) the version fields in clicinfo
We probably need some exposition here:
a) the "architecture version" presumably relates to a particular version of this spec - the spec should state  something like "CLIC implementations that conform to this version of this spec shall have an architecture version of '1'" (or whatever number you decide
b) I'm unsure what the "implementation version" field is for - is that free for the implementer to use?

5) programming CLICs in S and U modes
I don't think that a programmer can program a CLIC in supervisor and user modes without knowing the contents of cliccfg and clicinfo - I think that they should be available read-only in S and U CLIC spaces
Equally I'm not sure that poking through the interrupt space to find out which interrupts have been configured for your mode is all that safe, it might be appropriate to have a bit that's visible if an interrupt is available (say bit 3 of clinintattr)

That's probably enough for the moment .... 

    Paul Campbell

**Comment by kasanovic** [comment]
Please separate into separate issues.
