### ISSUE TITLE
missing xintthresh from table in section 6.1 summarizing overall behavior?

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-fast-interrupt#58]
In section 6.1. General interrupt overview:
The overall behavior is summarized in the following table: the Current p/ie/il fields represent the current privilege mode P (not software visible), interrupt enable in xstatus ie and interrupt level L in xintstatus; 
Should it instead say:
interrupt enable in xstatus ie and interrupt level L max(xintstatus.mil, xintthresh.th );

**Comment by dansmathers** [comment]
I also noticed it looks like 'ie' in the table should represent interrupt enable in xstatus.ie & clicintie[i].  only xstatus.ie is mentioned in the spec in this section.

**Comment by kasanovic** [comment]
Text and table needs clarification.

**Comment by dansmathers** [comment]
added pull request #118.  please review.  Thanks!

**Comment by Kevin-Andes** [comment]
Updated in spec checkin c26f4df2d57bd42f7f346d864725cfa640552b6f.
