### ISSUE TITLE
Legacy interrupts

### ISSUE THREAD

**Issue by MoonbaseOtago** [riscv/riscv-fast-interrupt#59]
The 3 sorts of legacy interrupts: software, timer and external each have 3 variants (M, S, and U) - without a CLIC they're implemented using the delegation mideleg/sideleg registers which effectively steer each interrupt to the M/S/U variants.

However in CLIC mode there are no mideleg/sideleg registers - the CLIC does the steering instead - I think it's worth calling out that each of the 3 timer interrupts are connected to the same single input.

We could also say that the 3 software interrupts are all connected to the same input, however there is no standard way to cause a software interrupt - we could fix that here simply by defining that in CLIC mode software interrupts are caused by writing a 1 to the appropriate interrupt pending bit.

The external interrupt is now the PLIC interrupt it's not an issue because it can already come in the 3 variants.

Paul Campbell

**Comment by kasanovic** [comment]
There is only hardware one timer interrupt in the original CLINT (from the memory-mapped mtimercmp circuit), the CLINT supervisor timer interrupt is generated by a machine-mode handler writing the stip bit.  Similarly, in CLIC mode, the machine-mode hardware timer handler can write a bit to indicate a supervisor timer interrupt, but now the effective "stip" bit is memory-mapped not in a CSR.

In CLIC mode, the software interrupts are all handled as memory-mapped IP bits (clicintip[]). Each can be routed to a supported privilege mode using clicintattr[].

Issue #89 proposes a standard mapping for the supervisor mode interrupts. 

We'll close this issue and continue discussion on #89.
