### ISSUE TITLE
20190610 change #10: Updated the maximum number of interrupt sources supported to 4096

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-fast-interrupt#69]
Draft 20190610 – separating multiple changes as individual issues to enable change tracking/approval from draft-20190610 doc upload.

20190610 change #10: Updated the maximum number of interrupt sources supported to 4096. 
Exccode changed from 9:0 to 11:0

**Comment by kasanovic** [comment]
Everyone agreed with change (actually 4095).
