### ISSUE TITLE
20200423 change #1: Added the filtering effect of Interrupt-Level Threshold (xintthresh) to pseudo code

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-fast-interrupt#70]
Draft 20200423 – separating multiple changes as individual issues to enable change tracking/approval from draft-20200423 doc upload.

- 20200423 change #1: Added the filtering effect of Interrupt-Level Threshold (xintthresh) to pseudo code for Next Interrupt Handler Address and Interrupt-Enable CSRs (xnxti) 
 
// Pseudo-code for csrrsi rd, mnxti, uimm[4:0] in M mode.
 mstatus |= uimm[4:0]; // Performed regardless of interrupt readiness.
 if (clic.priv==M && clic.level > mcause.pil && clic.level > mintthresh.th
     && (cliccfg.nvbits==0 || clicintattr.shv==0) ) {
   // The CLIC interrupt should be serviced before returning to the saved context,
   // unless it's a selectively hardware vectored interupt.
   mintstatus.mil = clic.level; // Update hart's interrupt level.
   mcause.exccode = clic.id;   // Update interrupt id.
   rd = TBASE + XLEN/8 * clic.id; // Return pointer to trap handler entry.
 } else {
   // No interrupt, or a selectively hardware vectored interrupt, or in non-CLIC mode.
   rd = 0;
 }

**Comment by kasanovic** [comment]
@Kevin-Andes Need to add more descriptive text to CSR section to describe threshold behavior.
