### ISSUE TITLE
prev issue 57 - 2: machine mode alignment

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-fast-interrupt#78]
Separating previous issue #57 into multiple issues for better tracking

2. machine mode alignment
the machine mode CLIC space needs to be protected from S/U accesses with a PMP, they have their own (implementation defined) alignment constraints - it's probably worth requiring that in systems with S and/or U modes that:
a) the region containing all the hart's machine mode CLIC spaces can be mapped with one PMP, and
b) that there is a spare PMP available for this purpose

**Comment by kasanovic** [comment]
If PMPs are implemented, unless M-mode aperture is explicitly enabled for S and U mode, they cannot access it, so no PMP entry is required to isolate M-mode aperture.
