### ISSUE TITLE
prev issue 57 - 3: supervisor/user/(hypervisor?) mode alignment

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-fast-interrupt#79]
Separating previous issue #57 into multiple issues for better tracking

3. supervisor/user/(hypervisor?) mode alignment
I think that this is already taken care of but it's worth making sure that a VM page (4k) alignment is required for the bases of each S/U mode CLIC region so that they can be mapped through the TLBs (especially on user mode)

**Comment by kasanovic** [comment]
This is a platform issue, but can be listed as a recommendation in commentary.
