### ISSUE TITLE
section 4.3 Changes to xie/xip CSRs: specify clearly that writes in clic mode to xie/xip are blocked

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-fast-interrupt#83]
Hi,
In section 4.3: Changes to xie/xip CSRs, it states:
The xie CSR appears hardwired to zero in CLIC mode, replaced by separate memory-mapped interrupt enables (clicintie[i]).

The xip CSR appears hardwired to zero in CLIC mode, replaced by separate memory-mapped interrupt pendings (clicintip[i]).

I assume this to mean that csr reads of xie/xip return zero.  I also assume this to mean that csr writes to csr registers xie/xip in CLIC mode do not change them.   Is this correct?  If so, can we state that more clearly what the behavior on writes is?  e.g., the "underlying state of the xie/xip csr registers is not writeable in clic mode" or something like that.

**Comment by Kevin-Andes** [comment]
Writes will be ignored and will not trap (no access exceptions). xie/xip always appear to be zero in CLIC mode.
