### ISSUE TITLE
Prototype DTS entry

### ISSUE THREAD

**Issue by MoonbaseOtago** [riscv/riscv-fast-interrupt#91]
Should the spec contain a prototypical DTS entry?

**Comment by kasanovic** [comment]
I think this would be useful as an appendix, though not part of normative text.  The primary parameters are the base address of the memory apertures and the number and routing of the interrupts.

**Comment by dansmathers** [comment]
AIA and PLIC specs do not contain DTS entries. However, Spike model does.  appending this DTS entry issue spike issue #242 
Closing.  Removing inaccurate DTS entry currently in the CLIC spec.
