### ISSUE TITLE
Name of the controller: CLIC or FLIC?

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-fast-interrupt#98]
Here I'm capturing the discussion in the TG meeting 2020/9/8:

It was suggested that CLIC and CLINT are too close in name and sound.

The CLINT name has propagated and is being used widely for the original scheme, despite not having a clear definition anywhere.

It is proposed we should therefore change the name of CLIC to something that is further lexically from CLINT.  One proposal is FLIC for "Fast Local Interrupt Controller".

**Comment by kasanovic** [comment]
CLIC name has been around for a while, and I don't think it really needs changing, and that CLINT and CLIC are reasonably distinguishable.

**Comment by Kevin-Andes** [comment]
The main problem is that these 2 names are NOT self-explanatory. Also, by having identical words and meaning, they are too confusing for millions of new readers in the future:

   Core Local INTerruptor (for CLINT)
   Core Local Interrupt Controller (for CLIC)

Therefore, before ratification, we better replace them with clear self-explanatory names to avoid confusion and misuse in the future.

**Comment by billhuffman** [comment]
I'm not eager to change, but a potential name for CLIC is CNIC, Core Nested Interrupt Controller.   That contains its biggest differentiation.

**Comment by kasanovic** [comment]
We're agreeing to sticking to CLIC as that's what we have been using.
